"""
visualization/kpi_cards.py — PHASE 3B: PART 1 — KPI Metric Row Wrapper

Pure layout presentation component. Maps the calculations generated by the 
central computation pipeline in core/analytics.py directly to frontend 
state dictionaries without computing standalone metrics.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Tuple
import pandas as pd
from core.column_registry import ColumnRegistry
from engine.analytics import UniversalAnalyticsEngine


# Milestone 3 / Issue 4 remediation: engine.analytics.ComplaintKPIEngine
# .compute_all() already computes ~21 scalar KPIs, each independently
# eligibility-gated by MetricEligibilityEngine, but the Executive KPI
# Command Row was structurally capped at exactly 5 cards by a fixed
# mapping_spec regardless of how many additional KPIs were actually
# eligible for the active role mappings. The primary 5 below are
# UNCHANGED — identical metric_id, display_name, kpi_key, unit, and
# formatting behavior — preserving full backward compatibility with every
# existing consumer (1_dashboard.py._render_single_kpi_card's sparkline
# lookup keys "total_volume"/"resolution_rate" are untouched). A second,
# additive pass now surfaces every other currently-eligible KPI from the
# same bundle.kpis dict using a business-impact-ordered priority list, so
# the platform's full computed KPI library becomes visible instead of
# being silently capped by frontend wiring.
_PRIMARY_KPI_SPEC: List[Tuple[str, str, str, str, bool]] = [
    ("total_volume", "Total Volume", "total_cases", "", True),
    ("resolution_rate", "Resolution Rate", "closure_rate", "%", True),
    ("avg_processing_latency", "Avg Latency (95th Clip)", "avg_resolution_time", "hrs", False),
    ("sla_compliance", "SLA Compliance", "sla_compliance_rate", "%", True),
    ("reopen_rate", "Escalation / Reopen Rate", "reopen_rate", "%", False),
]

# Business-impact-ordered secondary KPI surface. metric_id is deliberately
# set equal to kpi_key for every entry here (unlike the primary spec, whose
# metric_id/kpi_key pairs are historically decoupled) so downstream
# tooltip-correlation lookups (1_dashboard.py._METRIC_ID_TO_KPI_KEY) can
# resolve these new cards via a trivial identity mapping without altering
# the established primary-card correlation pattern.
_SECONDARY_KPI_ORDER: List[Tuple[str, str]] = [
    ("pending_rate", "Pending Rate"),
    ("backlog", "Backlog"),
    ("first_time_resolution_rate", "First-Time Resolution Rate"),
    ("avg_pending_age", "Avg Pending Age"),
    ("median_pending_age", "Median Pending Age"),
    ("p95_pending_age", "P95 Pending Age (Critical Tail)"),
    ("median_resolution_time", "Median Resolution Time"),
    ("p95_resolution_time", "P95 Resolution Time"),
    ("sla_breach_rate", "SLA Breach Rate"),
    ("unique_consumers", "Unique Consumers"),
    ("repeat_consumer_rate", "Repeat Consumer Rate"),
    ("mom_growth", "Month-over-Month Growth"),
    ("qoq_growth", "Quarter-over-Quarter Growth"),
    ("yoy_growth", "Year-over-Year Growth"),
]


def _format_kpi_card_value(numeric_val: float, unit: str) -> str:
    """Shared numeric formatting primitive for both the primary and
    secondary KPI card passes, keyed off engine.analytics.KPIResult.unit
    (e.g. '%', 'hrs', 'days', 'cases', 'consumers', ''). Never raises;
    unrecognized units degrade to plain thousands-separated formatting."""
    if unit == "%":
        return f"{numeric_val:.1f}%"
    if unit == "hrs":
        return f"{numeric_val:,.1f} hrs"
    if unit == "days":
        return f"{numeric_val:,.1f} days"
    return f"{numeric_val:,.0f}".strip()


def generate_metric_cards(
    df: pd.DataFrame, 
    registry: ColumnRegistry, 
    **kwargs: Any
) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    """
    Accepts raw workspace data frames, executes the core analytical engine pipeline, 
    and returns a structured payload compliant with frontend state rendering.

    Milestone 3 / Issue 4: now surfaces the full currently-eligible KPI set
    (primary pinned 5 + every other eligible scalar KPI from
    ComplaintKPIEngine.compute_all()), rather than a hardcoded 5-card cap.
    Return contract (List[Dict] schema + metadata dict schema) is
    unchanged — every existing consumer of this function continues to
    work without modification; it simply now receives a longer list when
    more roles are mapped.
    """
    metadata = {
        "engine_mode": "unified_core_bind",
        "metrics_computed": 0,
        "warning_count": 0,
        "critical_count": 0,
        "ineligible_count": 0,
    }
    
    if df.empty:
        return [], metadata

    # 1. Execute the Single Source of Truth Analytical Pipeline
    engine = UniversalAnalyticsEngine(registry)
    bundle = engine.run_complaint_analytics(df)
    kpis = bundle.kpis

    metric_cards: List[Dict[str, Any]] = []
    seen_metric_ids: set = set()

    # 2. Primary (pinned) KPI pass — behavior and formatting identical to
    #    the pre-Milestone-3 implementation.
    for metric_id, display_name, kpi_key, unit, higher_is_better in _PRIMARY_KPI_SPEC:
        # Resolved via .get() rather than direct bracket indexing. If a
        # future domain-specific KPI engine (HR/Revenue/Asset) or a KPI
        # rename ever returns a dict that does not carry this exact key,
        # this single card is cleanly skipped and counted as ineligible —
        # the same graceful-degradation contract the Smart KPI Eligibility
        # Engine enforces everywhere else — instead of raising an uncaught
        # KeyError that wipes out the entire Executive KPI Command Row via
        # the page-level exception handler in 1_dashboard.py._render_kpi_row.
        kpi_result = kpis.get(kpi_key)
        if kpi_result is None:
            metadata["ineligible_count"] += 1
            continue

        raw_val = kpi_result.value
        if raw_val is None or not kpi_result.is_eligible:
            metadata["ineligible_count"] += 1
            continue

        status_tier = kpi_result.status.upper()
        if status_tier == "CRITICAL":
            metadata["critical_count"] += 1
        elif status_tier == "WARNING":
            metadata["warning_count"] += 1

        try:
            numeric_val = float(raw_val)
        except (TypeError, ValueError):
            metadata["ineligible_count"] += 1
            continue

        metric_cards.append({
            "metric_id": metric_id,
            "display_name": display_name,
            "raw_value": numeric_val,
            "formatted_value": _format_kpi_card_value(numeric_val, unit),
            "delta_pct": 0.0,
            "trend_flag": "STABLE",
            "status_tier": status_tier,
        })
        seen_metric_ids.add(metric_id)
        metadata["metrics_computed"] += 1

    # 3. Secondary (full-eligible-set) KPI pass — additive, never
    #    duplicates a metric_id already rendered in the primary pass.
    for kpi_key, display_name in _SECONDARY_KPI_ORDER:
        if kpi_key in seen_metric_ids:
            continue
        kpi_result = kpis.get(kpi_key)
        if kpi_result is None:
            metadata["ineligible_count"] += 1
            continue

        raw_val = kpi_result.value
        if raw_val is None or not kpi_result.is_eligible:
            metadata["ineligible_count"] += 1
            continue

        status_tier = kpi_result.status.upper()
        if status_tier == "CRITICAL":
            metadata["critical_count"] += 1
        elif status_tier == "WARNING":
            metadata["warning_count"] += 1

        try:
            numeric_val = float(raw_val)
        except (TypeError, ValueError):
            metadata["ineligible_count"] += 1
            continue

        metric_cards.append({
            "metric_id": kpi_key,
            "display_name": display_name,
            "raw_value": numeric_val,
            "formatted_value": _format_kpi_card_value(numeric_val, kpi_result.unit),
            "delta_pct": 0.0,
            "trend_flag": "STABLE",
            "status_tier": status_tier,
        })
        seen_metric_ids.add(kpi_key)
        metadata["metrics_computed"] += 1

    return metric_cards, metadata


# def generate_metric_cards(
#     df: pd.DataFrame, 
#     registry: ColumnRegistry, 
#     **kwargs: Any
# ) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
#     """
#     Accepts raw workspace data frames, executes the core analytical engine pipeline, 
#     and returns a structured payload compliant with frontend state rendering.
#     """
#     metadata = {
#         "engine_mode": "unified_core_bind",
#         "metrics_computed": 0,
#         "warning_count": 0,
#         "critical_count": 0
#     }
    
#     if df.empty:
#         return [], metadata

#     # 1. Execute the Single Source of Truth Analytical Pipeline
#     engine = UniversalAnalyticsEngine(registry)
#     bundle = engine.run_complaint_analytics(df)
#     kpis = bundle.kpis

#     metric_cards = []

#     # 2. Configured presentation map matching frontend requirements
#     mapping_spec = [
#         ("total_volume", "Total Volume", kpis["total_cases"].value, "", True),
#         ("resolution_rate", "Resolution Rate", kpis["closure_rate"].value, "%", True),
#         ("avg_processing_latency", "Avg Latency (95th Clip)", kpis["avg_resolution_time"].value, "hrs", False),
#         ("sla_compliance", "SLA Compliance", kpis["sla_compliance_rate"].value, "%", True),
#         ("reopen_rate", "Escalation / Reopen Rate", kpis["reopen_rate"].value, "%", False),
#     ]

#   for metric_id, display_name, raw_val, unit, higher_is_better in mapping_spec:
#         # Pull core evaluation statuses straight from analytics engine output
#         core_status = kpis["total_cases"].status if metric_id == "total_volume" else kpis[
#             "closure_rate" if metric_id == "resolution_rate" else
#             "avg_resolution_time" if metric_id == "avg_processing_latency" else
#             "sla_compliance_rate" if metric_id == "sla_compliance" else "reopen_rate"
#         ].status
        
#         status_tier = core_status.upper()
#         if status_tier == "CRITICAL":
#             metadata["critical_count"] += 1
#         elif status_tier == "WARNING":
#             metadata["warning_count"] += 1

#         # Safe presentation string formatting
#         if unit == "%":
#             formatted_value = f"{raw_val:.1f}%"
#         elif unit == "hrs":
#             formatted_value = f"{raw_val:,.1f} hrs"
#         else:
#             formatted_value = f"{raw_val:,.0f}".strip()

#         # Build consistent state payloads for frontend card loops
#         metric_cards.append({
#             "metric_id": metric_id,
#             "display_name": display_name,
#             "raw_value": float(raw_val),
#             "formatted_value": formatted_value,
#             "delta_pct": 0.0,  
#             "trend_flag": "STABLE",
#             "status_tier": status_tier,
#         })
#         metadata["metrics_computed"] += 1

#     return metric_cards, metadata